### ISSUE TITLE
Example of team tracking card?

### ISSUE THREAD

**Issue by timoverwoest** [joosthoi1/hockey-team-tracker#3]
Hi Joost,
Nice work, thank you for the effort!
Could you elaborate a bit more on the custom card integration? Which custom card do you use? And do you have some example YAML code?
Rgrds
Timo

**Comment by joosthoi1** [comment]
Thanks for painting it out. I updated the reader to show which card is used in the example. (https://github.com/MadSnuif/hockeynl-card)
